### ISSUE TITLE
Prototype checklist and questions

### ISSUE THREAD

**Issue by runemadsen** [designsystemsinternational/mechanic#2]
A few things I'm working through

- [x] Canvas image preview
- [x] canvas image export
- [x] Canvas video preview
- [x] Canvas video export capture
- [x] SVG image preview 
- [x] SVG image export
- [x] SVG video preview
- [x] SVG video export
- [x] React preview
- [x] React export
- [x] Fast preview
- [x] Design function inside iframe
- [x] Random seed from preview to download
- [x] Load webfonts
- [x] bypass `requestAnimationFrame` on export
- [ ] Automatic creation of inputs for string and integer

## Questions

- Where do we set the frameRate of the video? In settings? Could this be bound to the custom `requestAnimationFrame`?
- Where do we specify which format to export to? Should the function define `type: "canvas"` so we know the conversion possibilities?
- Do we build in handling of React or do people need to use `renderToString`? If we build it in, the el can also use React's virtual dom while rendering. With the `iframe` changes, we can have a specific runner per file. One for canvas, one for SVG, one for React, and people can write any runners needed to support other libraries!
- Use OffscreenCanvas when rendering for download / api?
- Is it odd that SVG animation is done via JS and not via `<animate>` attributes?
- Figure out a way to reuse els across previews
- Do we put `randomSeed` in params or `usesRandom:true` in settings?
- Webfonts can be loaded via [WebFontLoader](https://github.com/typekit/webfontloader) (supports Google Fonts) or [FontFaceObserver](https://github.com/bramstein/fontfaceobserver) (very small, custom fonts only). Should we build any of them into mechanic or just have a good example? I'm leaning towards the latter.
- We have a time vs frame problem. Do we do like CCapture or just have `addFrame()` without stubbing the timing methods? What if people use `setTimeout()`?

**Comment by runemadsen** [comment]
Renderers: yes: package or file.

**Comment by runemadsen** [comment]
For responsive designs: scale to fit by scaling the DOM (won't be fast). Can rename to optimize preview.

**Comment by runemadsen** [comment]
Go back to earlier versions? Preview is arrows?

**Comment by runemadsen** [comment]
Grid of options? Select which to export.

**Comment by runemadsen** [comment]
When you define the type, you can select which format to export to.
